### ISSUE TITLE
Column count in different devices

### ISSUE THREAD

**Issue by ghost** [OZMOPOL/OZMO-ANDROID#4]
@arcadesmasher 
There are two parameters of "StaggeredGridView" that can set column count in portrait and landscape mode. Could you please write functions for changing column counts according to device type? 

void updateColumnCountsPosts()
void updateColumnCountsRooms()

**Comment by arcadesmasher** [comment]
I'm currently outside right now, I will though have a look at it tonight.

**Comment by arcadesmasher** [comment]
Taking notes on here:

```
public boolean isTablet(){
    DisplayMetrics metrics = new DisplayMetrics();
    getActivity().getWindowManager().getDefaultDisplay().getMetrics(metrics);
    int width = metrics.widthPixels;
    int height = metrics.heightPixels;
    if (width > 1023 || height > 1023){
        return true;
    } else {
       return false;
    }
}

public void updateColumnCountForRooms(){
    if(isTablet()){
        gridView.setColumnCount(5);
    } else {
        gridView.setColumnCount(1);
    }
}
```

Will fix the implementation tomorrow. I will use this method to identify the type of the device used. The contents of the "updateColumnCountForRooms" method will of course be fixed for the portrait/landscape views.

Didn't commit anything for now "intentionally" because I'm almost asleep and didn't wanna mess things up both on the Hub and on my own filesystem.
